# machineLearning   신민수

### 신용카드 사용자 연체 예측 AI 

### **[ 컬럼 정보 ]**
- index
- gender: 성별
- car: 차량 소유 여부
- reality: 부동산 소유 여부
- child_num: 자녀 수
- income_total: 연간 소득
- income_type: 소득 분류 ['Commercial associate', 'Working', 'State servant', 'Pensioner', 'Student']

- edu_type: 교육 수준 ['Higher education' ,'Secondary / secondary special', 'Incomplete higher', 'Lower secondary', 'Academic degree']

- family_type: 결혼 여부 ['Married', 'Civil marriage', 'Separated', 'Single / not married', 'Widow']

- house_type: 생활 방식 ['Municipal apartment', 'House / apartment', 'With parents','Co-op apartment', 'Rented apartment', 'Office apartment']

- DAYS_BIRTH: 출생일 데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전에 태어났음을 의미

- DAYS_EMPLOYED: 업무 시작일 데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전부터 일을 시작함을 의미)
  -양수 값은 고용되지 않은 상태를 의미함

- FLAG_MOBIL: 핸드폰 소유 여부
- work_phone: 업무용 전화 소유 여부
- phone: 전화 소유 여부
- email: 이메일 소유 여부
- occyp_type: 직업 유형	
  - Laborers                 4512
Core staff               2646
Sales staff              2539
Managers                 2167
Drivers                  1575
High skill tech staff    1040
Accountants               902
Medicine staff            864
Cooking staff             457
Security staff            424
Cleaning staff            403
Private service staff     243
Low-skill Laborers        127
Waiters/barmen staff      124
Secretaries                97
Realty agents              63
HR staff                   62
IT staff                   41
												
- family_size: 가족 규모
- begin_month: 신용카드 발급 월(데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 한 달 전에 신용카드를 발급함을 의미)
- credit: 사용자의 신용카드 대금 연체를 기준으로 한 신용도
  - 낮을 수록 높은 신용의 신용카드 사용자를 의미함


# [1] 데이터 탐색

In [92]:
# 모듈 로딩
import pandas as pd

In [93]:
df = pd.read_csv('./creditcard/train.csv', index_col= 0 )

In [94]:
df.shape

(26457, 19)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26457 entries, 0 to 26456
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   gender         26457 non-null  object 
 1   car            26457 non-null  object 
 2   reality        26457 non-null  object 
 3   child_num      26457 non-null  int64  
 4   income_total   26457 non-null  float64
 5   income_type    26457 non-null  object 
 6   edu_type       26457 non-null  object 
 7   family_type    26457 non-null  object 
 8   house_type     26457 non-null  object 
 9   DAYS_BIRTH     26457 non-null  int64  
 10  DAYS_EMPLOYED  26457 non-null  int64  
 11  FLAG_MOBIL     26457 non-null  int64  
 12  work_phone     26457 non-null  int64  
 13  phone          26457 non-null  int64  
 14  email          26457 non-null  int64  
 15  occyp_type     18286 non-null  object 
 16  family_size    26457 non-null  float64
 17  begin_month    26457 non-null  float64
 18  credit

In [96]:
# 결측치 확인
df.isnull().sum()

gender              0
car                 0
reality             0
child_num           0
income_total        0
income_type         0
edu_type            0
family_type         0
house_type          0
DAYS_BIRTH          0
DAYS_EMPLOYED       0
FLAG_MOBIL          0
work_phone          0
phone               0
email               0
occyp_type       8171
family_size         0
begin_month         0
credit              0
dtype: int64

In [97]:
# 직업 컬럼 결측치 
df = df.fillna('no')

In [98]:
df.head()

gender car reality  child_num  income_total           income_type  \
index                                                                     
0          F   N       N          0      202500.0  Commercial associate   
1          F   N       Y          1      247500.0  Commercial associate   
2          M   Y       Y          0      450000.0               Working   
3          F   N       Y          0      202500.0  Commercial associate   
4          F   Y       Y          0      157500.0         State servant   

                            edu_type     family_type           house_type  \
index                                                                       
0                   Higher education         Married  Municipal apartment   
1      Secondary / secondary special  Civil marriage    House / apartment   
2                   Higher education         Married    House / apartment   
3      Secondary / secondary special         Married    House / apartment   
4                   Higher education         Married    House / apartment   

       DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  work_phone  phone  email  \
index                                                                    
0          -13899          -4709           1           0      0      0   
1          -11380          -1540           1           0      0      1   
2          -19087          -4434           1           0      1      0   
3          -15088          -2092           1           0      1      0   
4          -15037          -2105           1           0      0      0   

        occyp_type  family_size  begin_month  credit  
index                                                 
0               no          2.0         -6.0     1.0  
1         Laborers          3.0         -5.0     1.0  
2         Managers          2.0        -22.0     2.0  
3      Sales staff          2.0        -37.0     0.0  
4         Managers          2.0        -26.0     2.0

In [99]:
# target 신용도 종류 & 수 확인
df['credit'].value_counts()

2.0    16968
1.0     6267
0.0     3222
Name: credit, dtype: int64

In [100]:
# 직업 컬럼 종류 및 수 확인
df['occyp_type'].value_counts()

no                       8171
Laborers                 4512
Core staff               2646
Sales staff              2539
Managers                 2167
Drivers                  1575
High skill tech staff    1040
Accountants               902
Medicine staff            864
Cooking staff             457
Security staff            424
Cleaning staff            403
Private service staff     243
Low-skill Laborers        127
Waiters/barmen staff      124
Secretaries                97
Realty agents              63
HR staff                   62
IT staff                   41
Name: occyp_type, dtype: int64

# [2] 데이터 레이블 인코딩

In [101]:
from sklearn.preprocessing import LabelEncoder

In [102]:
# 문자열 컬럼만 따로 추출
df1 = df.copy()

df_str = df[['gender','car','reality','income_type','edu_type','family_type','house_type','occyp_type']]

for col in df_str:
  col = str(col)
  encoder = LabelEncoder()
  encoder.fit(df[col])
  labels = encoder.transform(df[col]) # 숫자 라벨 생성
  df1[col] = labels
  
  print(col)
  print(labels) 
  print(encoder.classes_) # 바꾸기 전 속성 체크
  print('------------------------------------------------------')

gender
[0 0 1 ... 0 1 0]
['F' 'M']
------------------------------------------------------
car
[0 0 1 ... 1 0 0]
['N' 'Y']
------------------------------------------------------
reality
[0 1 1 ... 0 1 0]
['N' 'Y']
------------------------------------------------------
income_type
[0 0 4 ... 4 4 4]
['Commercial associate' 'Pensioner' 'State servant' 'Student' 'Working']
------------------------------------------------------
edu_type
[1 4 1 ... 4 2 4]
['Academic degree' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Secondary / secondary special']
------------------------------------------------------
family_type
[1 0 1 ... 0 3 0]
['Civil marriage' 'Married' 'Separated' 'Single / not married' 'Widow']
------------------------------------------------------
house_type
[2 1 1 ... 5 1 1]
['Co-op apartment' 'House / apartment' 'Municipal apartment'
 'Office apartment' 'Rented apartment' 'With parents']
------------------------------------------------------
occyp_type
[18  8 10 ... 

# [3] input_data, target 나누기 

In [103]:
df1

gender  car  reality  child_num  income_total  income_type  edu_type  \
index                                                                         
0           0    0        0          0      202500.0            0         1   
1           0    0        1          1      247500.0            0         4   
2           1    1        1          0      450000.0            4         1   
3           0    0        1          0      202500.0            0         4   
4           0    1        1          0      157500.0            2         1   
...       ...  ...      ...        ...           ...          ...       ...   
26452       0    0        0          2      225000.0            2         4   
26453       0    0        1          1      180000.0            4         1   
26454       0    1        0          0      292500.0            4         4   
26455       1    0        1          0      171000.0            4         2   
26456       0    0        0          0       81000.0            4         4   

       family_type  house_type  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  \
index                                                                   
0                1           2      -13899          -4709           1   
1                0           1      -11380          -1540           1   
2                1           1      -19087          -4434           1   
3                1           1      -15088          -2092           1   
4                1           1      -15037          -2105           1   
...            ...         ...         ...            ...         ...   
26452            1           1      -12079          -1984           1   
26453            2           1      -15291          -2475           1   
26454            0           5      -10082          -2015           1   
26455            3           1      -10145           -107           1   
26456            0           1      -19569          -1013           1   

       work_phone  phone  email  occyp_type  family_size  begin_month  credit  
index                                                                          
0               0      0      0          18          2.0         -6.0     1.0  
1               0      0      1           8          3.0         -5.0     1.0  
2               0      1      0          10          2.0        -22.0     2.0  
3               0      1      0          14          2.0        -37.0     0.0  
4               0      0      0          10          2.0        -26.0     2.0  
...           ...    ...    ...         ...          ...          ...     ...  
26452           0      0      0           3          4.0         -2.0     1.0  
26453           0      0      0          18          2.0        -47.0     2.0  
26454           0      0      0           3          2.0        -25.0     2.0  
26455           0      0      0           8          1.0        -59.0     2.0  
26456           0      0      0          16          2.0         -9.0     2.0  

[26457 rows x 19 columns]

In [104]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# 전체 데이터
target = df1['credit'].values
input_data =df1[df1.columns[:18]].values

print(target.shape)
print(input_data)

# 전체 데이터
train_X,test_X,train_y,test_y = train_test_split(input_data,target,test_size = 0.2, stratify=target ,random_state=42 )

(26457,)
[[  0.   0.   0. ...  18.   2.  -6.]
 [  0.   0.   1. ...   8.   3.  -5.]
 [  1.   1.   1. ...  10.   2. -22.]
 ...
 [  0.   1.   0. ...   3.   2. -25.]
 [  1.   0.   1. ...   8.   1. -59.]
 [  0.   0.   0. ...  16.   2.  -9.]]


In [105]:
# 랜덤추출로 데이터 1000행 추출
df2= df1.sample(n=1000,random_state=42)

# 3000개 램덤추출 데이터
target_random = df2['credit'].values
input_random = df2[df2.columns[:18]].values

print(target_random.shape)
print(input_random.shape)

# 랜덤추출 데이터
train_X_r, test_X_r, train_y_r, test_y_r = train_test_split(input_random,target_random, test_size = 0.2, stratify = target_random ,random_state = 42 )

(1000,)
(1000, 18)


# [4] 모든 분류기 점수 확인 

In [106]:
# 필터 타입에 해당하는 sklearn에 존재하는 모든 모델 이름과 객체 리스트로 반환
from sklearn.utils import all_estimators
models = all_estimators(type_filter = 'classifier')

# 각 모델들 훈련시키고 정확도 추출
scores = []
for name, model in models:
    try:
        # 모델 객체 생성
        md = model()
        # 학습
        md.fit(train_X_r, train_y_r)
        # 평가
        result = md.score(test_X_r, test_y_r)
    
        scores.append((name, result))
    except:
        pass

/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/semi_supervised/_label_propagation.py:222: RuntimeWarning: invalid value encountered in true_divide
  proba

In [17]:
scores

[('AdaBoostClassifier', 0.625),
 ('BaggingClassifier', 0.57),
 ('BernoulliNB', 0.635),
 ('CalibratedClassifierCV', 0.635),
 ('DecisionTreeClassifier', 0.485),
 ('DummyClassifier', 0.635),
 ('ExtraTreeClassifier', 0.57),
 ('ExtraTreesClassifier', 0.63),
 ('GaussianNB', 0.6),
 ('GaussianProcessClassifier', 0.635),
 ('GradientBoostingClassifier', 0.625),
 ('HistGradientBoostingClassifier', 0.635),
 ('KNeighborsClassifier', 0.53),
 ('LabelPropagation', 0.125),
 ('LabelSpreading', 0.125),
 ('LinearDiscriminantAnalysis', 0.635),
 ('LinearSVC', 0.53),
 ('LogisticRegression', 0.63),
 ('LogisticRegressionCV', 0.63),
 ('MLPClassifier', 0.545),
 ('NearestCentroid', 0.165),
 ('PassiveAggressiveClassifier', 0.635),
 ('Perceptron', 0.635),
 ('QuadraticDiscriminantAnalysis', 0.41),
 ('RandomForestClassifier', 0.68),
 ('RidgeClassifier', 0.635),
 ('RidgeClassifierCV', 0.635),
 ('SGDClassifier', 0.635),
 ('SVC', 0.635)]

# [5] 분류기 선정 및 전체 데이터 대입

In [16]:
# 랜덤포레스트, 로지스틱회귀,  SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

model_RF = RandomForestClassifier()
model_LR = LogisticRegression()
model_SVC = SVC()

model_RF.fit(train_X,train_y)
model_LR.fit(train_X,train_y)
model_SVC.fit(train_X,train_y)

SVC()

In [19]:
print('[ RandomForestClassifier ] -----------')
print('train점수:',model_RF.score(train_X,train_y))
print('test점수:', model_RF.score(test_X,test_y))

[ RandomForestClassifier ] -----------
train점수: 0.9776045357902197
test점수: 0.7061602418745276


In [20]:
print('[ LogisticRegression ] ---------------')
print('train점수:',model_LR.score(train_X,train_y))
print('test점수:', model_LR.score(test_X,test_y))

[ LogisticRegression ] ---------------
train점수: 0.6413418379399953
test점수: 0.6413454270597128


In [ ]:
print('[ SVC ] ------------------------------')
print('train점수:',model_SVC.score(train_X,train_y))
print('test점수:', model_SVC.score(test_X,test_y))

[ SVC ] ------------------------------
train점수: 0.6413418379399953
test점수: 0.6413454270597128


# [6] 추가 가공
- 1. 값이 모두 같은 불필요한 컬럼 제거(FLAG_MOBIL 컬럼 제거) -> 변화X
- 결측치가 30% 정도 있는 컬럼 변경 or 삭제
- 독립변수끼리 상관관계 높은 변수 제거 
    - child_num~family_size
    - DAYS_BIRTH + occyp_type ~ DAYS_EMPLOYED
- 스케일러

In [108]:
df1['FLAG_MOBIL'].value_counts()

1    26457
Name: FLAG_MOBIL, dtype: int64

In [109]:
# 1. 불필요한 컬럼 제거 (FLAG_MOBIL)
df1_drop = df1.drop('FLAG_MOBIL',axis=1)

In [110]:
df1

gender  car  reality  child_num  income_total  income_type  edu_type  \
index                                                                         
0           0    0        0          0      202500.0            0         1   
1           0    0        1          1      247500.0            0         4   
2           1    1        1          0      450000.0            4         1   
3           0    0        1          0      202500.0            0         4   
4           0    1        1          0      157500.0            2         1   
...       ...  ...      ...        ...           ...          ...       ...   
26452       0    0        0          2      225000.0            2         4   
26453       0    0        1          1      180000.0            4         1   
26454       0    1        0          0      292500.0            4         4   
26455       1    0        1          0      171000.0            4         2   
26456       0    0        0          0       81000.0            4         4   

       family_type  house_type  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  \
index                                                                   
0                1           2      -13899          -4709           1   
1                0           1      -11380          -1540           1   
2                1           1      -19087          -4434           1   
3                1           1      -15088          -2092           1   
4                1           1      -15037          -2105           1   
...            ...         ...         ...            ...         ...   
26452            1           1      -12079          -1984           1   
26453            2           1      -15291          -2475           1   
26454            0           5      -10082          -2015           1   
26455            3           1      -10145           -107           1   
26456            0           1      -19569          -1013           1   

       work_phone  phone  email  occyp_type  family_size  begin_month  credit  
index                                                                          
0               0      0      0          18          2.0         -6.0     1.0  
1               0      0      1           8          3.0         -5.0     1.0  
2               0      1      0          10          2.0        -22.0     2.0  
3               0      1      0          14          2.0        -37.0     0.0  
4               0      0      0          10          2.0        -26.0     2.0  
...           ...    ...    ...         ...          ...          ...     ...  
26452           0      0      0           3          4.0         -2.0     1.0  
26453           0      0      0          18          2.0        -47.0     2.0  
26454           0      0      0           3          2.0        -25.0     2.0  
26455           0      0      0           8          1.0        -59.0     2.0  
26456           0      0      0          16          2.0         -9.0     2.0  

[26457 rows x 19 columns]

In [111]:
# 전체 데이터
target = df1_drop['credit']
input_data = df1_drop[df1_drop.columns[:17]]

print(target.shape)
print(input_data.info())

# 전체 데이터
train_X,test_X,train_y,test_y = train_test_split(input_data,target,test_size = 0.2, stratify=target ,random_state=42 )

# 스케일링-------------------------------------------------------------------
from sklearn.preprocessing import StandardScaler
# 변형 객체 생성
std_scaler = StandardScaler()

# 훈련데이터의 모수 분포 저장
std_scaler.fit(train_X)

# 훈련 데이터 스케일링
train_X_scaled = std_scaler.transform(train_X)

# 테스트 데이터의 스케일링
test_X_scaled = std_scaler.transform(test_X)

train_X_scaled

(26457,)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26457 entries, 0 to 26456
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   gender         26457 non-null  int64  
 1   car            26457 non-null  int64  
 2   reality        26457 non-null  int64  
 3   child_num      26457 non-null  int64  
 4   income_total   26457 non-null  float64
 5   income_type    26457 non-null  int64  
 6   edu_type       26457 non-null  int64  
 7   family_type    26457 non-null  int64  
 8   house_type     26457 non-null  int64  
 9   DAYS_BIRTH     26457 non-null  int64  
 10  DAYS_EMPLOYED  26457 non-null  int64  
 11  work_phone     26457 non-null  int64  
 12  phone          26457 non-null  int64  
 13  email          26457 non-null  int64  
 14  occyp_type     26457 non-null  int64  
 15  family_size    26457 non-null  float64
 16  begin_month    26457 non-null  float64
dtypes: float64(3), int64(14)
memory usage: 3.

array([[ 1.4194919 , -0.78431861, -1.43168146, ..., -0.48649325,
        -1.2936427 , -0.23029796],
       [ 1.4194919 , -0.78431861,  0.69847939, ..., -0.48649325,
         0.87885177,  1.33809263],
       [-0.70447742,  1.27499206,  0.69847939, ..., -1.32417606,
        -0.20739547,  0.55389733],
       ...,
       [ 1.4194919 ,  1.27499206, -1.43168146, ..., -1.15663949,
        -0.20739547,  0.61422005],
       [ 1.4194919 ,  1.27499206,  0.69847939, ..., -1.15663949,
        -1.2936427 ,  0.19196104],
       [-0.70447742, -0.78431861, -1.43168146, ...,  0.51872613,
         0.87885177,  0.61422005]])

In [112]:
# 랜덤포레스트, 로지스틱회귀,  SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

model_RF = RandomForestClassifier()
model_LR = LogisticRegression()
model_SVC = SVC()

model_RF.fit(train_X_scaled,train_y)
model_LR.fit(train_X_scaled,train_y)
model_SVC.fit(train_X_scaled,train_y)

print('[ RandomForestClassifier ] -----------')
print('train점수:',model_RF.score(train_X_scaled,train_y))
print('test점수:', model_RF.score(test_X_scaled,test_y))

[ RandomForestClassifier ] -----------
train점수: 0.9776517836050083
test점수: 0.7031368102796675


In [113]:
print('[ LogisticRegression ] ---------------')
print('train점수:',model_LR.score(train_X_scaled,train_y))
print('test점수:', model_LR.score(test_X_scaled,test_y))

[ LogisticRegression ] ---------------
train점수: 0.6423340420505551
test점수: 0.641912320483749


In [114]:
print('[ SVC ] ------------------------------')
print('train점수:',model_SVC.score(train_X_scaled,train_y))
print('test점수:', model_SVC.score(test_X_scaled,test_y))

[ SVC ] ------------------------------
train점수: 0.6566028821167021
test점수: 0.6473922902494331


In [28]:
df1.corr() 

gender       car   reality  child_num  income_total  \
gender         1.000000  0.362320 -0.048927   0.076731      0.198455   
car            0.362320  1.000000 -0.016599   0.101846      0.213432   
reality       -0.048927 -0.016599  1.000000   0.000435      0.035377   
child_num      0.076731  0.101846  0.000435   1.000000      0.032186   
income_total   0.198455  0.213432  0.035377   0.032186      1.000000   
income_type    0.103083  0.048361 -0.048468   0.106498     -0.075175   
edu_type       0.006351 -0.105567  0.011535  -0.049002     -0.225893   
family_type   -0.101969 -0.124280  0.028144  -0.161222     -0.005802   
house_type     0.067437  0.018617 -0.177957   0.023120     -0.004514   
DAYS_BIRTH     0.201138  0.156883 -0.130241   0.332816      0.064155   
DAYS_EMPLOYED -0.172990 -0.159260  0.097947  -0.228159     -0.166478   
FLAG_MOBIL          NaN       NaN       NaN        NaN           NaN   
work_phone     0.064316  0.026124 -0.208648   0.051521     -0.034207   
phone         -0.027078 -0.013730 -0.065553  -0.010555      0.019013   
email          0.000108  0.018904  0.051085   0.016120      0.089882   
occyp_type    -0.130283 -0.121225  0.047347  -0.135173     -0.093062   
family_size    0.111060  0.149463 -0.006667   0.890530      0.023839   
begin_month    0.007707 -0.029955  0.003863  -0.007229     -0.018047   
credit         0.001562  0.007761 -0.009387   0.004081      0.008555   

               income_type  edu_type  family_type  house_type  DAYS_BIRTH  \
gender            0.103083  0.006351    -0.101969    0.067437    0.201138   
car               0.048361 -0.105567    -0.124280    0.018617    0.156883   
reality          -0.048468  0.011535     0.028144   -0.177957   -0.130241   
child_num         0.106498 -0.049002    -0.161222    0.023120    0.332816   
income_total     -0.075175 -0.225893    -0.005802   -0.004514    0.064155   
income_type       1.000000  0.056688    -0.050790    0.033013    0.211466   
edu_type          0.056688  1.000000     0.008717   -0.039668   -0.166666   
family_type      -0.050790  0.008717     1.000000    0.007189   -0.104556   
house_type        0.033013 -0.039668     0.007189    1.000000    0.210021   
DAYS_BIRTH        0.211466 -0.166666    -0.104556    0.210021    1.000000   
DAYS_EMPLOYED    -0.361347  0.120944     0.125207   -0.105835   -0.616776   
FLAG_MOBIL             NaN       NaN          NaN         NaN         NaN   
work_phone        0.161857 -0.023778    -0.065483    0.031381    0.178752   
phone             0.004436 -0.045179    -0.014388   -0.019003   -0.029247   
email            -0.020060 -0.095640    -0.015427    0.013517    0.111238   
occyp_type       -0.198431  0.084669     0.056889   -0.064466   -0.331310   
family_size       0.107698 -0.041345    -0.545149    0.005010    0.298108   
begin_month       0.002750  0.013824     0.030711    0.030556    0.057306   
credit           -0.008163  0.013780    -0.005230   -0.009023   -0.025187   

               DAYS_EMPLOYED  FLAG_MOBIL  work_phone     phone     email  \
gender             -0.172990         NaN    0.064316 -0.027078  0.000108   
car                -0.159260         NaN    0.026124 -0.013730  0.018904   
reality             0.097947         NaN   -0.208648 -0.065553  0.051085   
child_num          -0.228159         NaN    0.051521 -0.010555  0.016120   
income_total       -0.166478         NaN   -0.034207  0.019013  0.089882   
income_type        -0.361347         NaN    0.161857  0.004436 -0.020060   
edu_type            0.120944         NaN   -0.023778 -0.045179 -0.095640   
family_type         0.125207         NaN   -0.065483 -0.014388 -0.015427   
house_type         -0.105835         NaN    0.031381 -0.019003  0.013517   
DAYS_BIRTH         -0.616776         NaN    0.178752 -0.029247  0.111238   
DAYS_EMPLOYED       1.000000         NaN   -0.241827 -0.007749 -0.091090   
FLAG_MOBIL               NaN         NaN         NaN       NaN       NaN   
work_phone         -0.241827         NaN    1.0

# [7] 하이퍼파라미터 최적화

In [17]:
from sklearn.model_selection import GridSearchCV

# 랜덤포레스트 하이퍼파리미터 최적화

# Grid_Search
param_range = [5,10,15]
param_grid = { 
    'criterion' : ['gini','entropy'],
    'max_depth':param_range,
    'max_features':param_range,
    'min_samples_split': param_range,
}

GS = GridSearchCV(
    estimator = model_RF, 
    param_grid = param_grid,
    cv = 5,
    scoring='accuracy',
    return_train_score = True
)

In [18]:
GS.fit(train_X,train_y)

KeyboardInterrupt: 

In [31]:
# 최적의 파라미터 확인
print('[ RandomForestClassifier 하이퍼 파라미터 최적화]')
print('1.모델 최고점수:',GS.best_score_)
print('2.모델 최적 하이퍼 파라미터:', GS.best_params_)

[ RandomForestClassifier 하이퍼 파라미터 최적화]
1.모델 최고점수: 0.68875
2.모델 최적 하이퍼 파라미터: {'criterion': 'gini', 'max_depth': 5, 'max_features': 5, 'min_samples_split': 10}


In [51]:
# SVC 하이퍼파리미터 최적화

# Grid_Search
param_range = [0.01,0.1,1,10,100]
param_grid = { 
    'C' : param_range,
    'kernel':['linear'], #'sigmoid', 'poly', 'rbf' 
    'gamma': param_range
}

GS = GridSearchCV(
    estimator = model_SVC, 
    param_grid = param_grid,
    cv = 5,
    scoring='accuracy',
    return_train_score = True
)

In [52]:
GS.fit(train_X_r,train_y_r)

# 최적의 파라미터 확인
print('[ SVC 하이퍼 파라미터 최적화 ]')
print('1.모델 최고점수:',GS.best_score_)
print('2.모델 최적 하이퍼 파라미터:', GS.best_params_)

In [41]:
# 로지스틱회귀 하이퍼파라미터 최적화
from sklearn.metrics import accuracy_score, roc_auc_score

# 로지스틱 회귀 모델 생성 및 학습
lr_clf = LogisticRegression()

In [46]:
params = {'penalty':['l2', 'l1'],
        'C':[0.01, 0.1, 1, 10, 100]}

GS = GridSearchCV(lr_clf, param_grid=params, scoring='accuracy', cv=3)
GS.fit(train_X_scaled, train_y)
print('최적 하이퍼 파라미터 :{0}, 최적 평균 정확도 :{1:.3f}'.format(GS.best_params_,
                                                GS.best_score_))

최적 하이퍼 파라미터 :{'C': 0.1, 'penalty': 'l2'}, 최적 평균 정확도 :0.642


/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solve

In [47]:
# 최적의 파라미터 확인
print('[ LogisticRegression 하이퍼 파라미터 최적화 ]')
print('1.모델 최고점수:',GS.best_score_)
print('2.모델 최적 하이퍼 파라미터:', GS.best_params_)

[ LogisticRegression 하이퍼 파라미터 최적화 ]
1.모델 최고점수: 0.6424285376801323
2.모델 최적 하이퍼 파라미터: {'C': 0.1, 'penalty': 'l2'}


# [8] 교차검정

In [48]:
from sklearn.model_selection import cross_val_score
print('RF:',cross_val_score(model_RF, train_X, train_y))
print('LR:',cross_val_score(model_LR, train_X, train_y))
print('SVC:',cross_val_score(model_SVC, train_X, train_y))

RF: [0.70139381 0.70139381 0.70021262 0.70422868 0.70092133]
LR: [0.64138909 0.64138909 0.64115285 0.64138909 0.64138909]
SVC: [0.64138909 0.64138909 0.64115285 0.64138909 0.64138909]


In [49]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

#예측해보기
y_pred = model_SVC.predict(test_X)

# 분석결과 확인
svm_report = classification_report(test_y, y_pred)
print(svm_report)

# 오차행렬인 컴퓨전 메트릭스 확인
svm_matrix = confusion_matrix(test_y, y_pred)
print(svm_matrix)

#정확도 비교해보기
svm_accuracy = accuracy_score(test_y, y_pred)
print('SVM의 정확도 : ',svm_accuracy)

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       644
         1.0       0.00      0.00      0.00      1254
         2.0       0.64      1.00      0.78      3394

    accuracy                           0.64      5292
   macro avg       0.21      0.33      0.26      5292
weighted avg       0.41      0.64      0.50      5292

[[   0    0  644]
 [   0    0 1254]
 [   0    0 3394]]
SVM의 정확도 :  0.6413454270597128


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [115]:
test1 = pd.read_csv('./creditcard/test.csv',index_col=0)

In [43]:
model_final = RandomForestClassifier(criterion= 'gini', max_depth= 5, max_features= 5, min_samples_split= 10)
model_final.fit(train_X,train_y)

RandomForestClassifier(max_depth=5, max_features=5, min_samples_split=10)

In [116]:
# 직업 컬럼 결측치 
test1 = test1.fillna('no')

# 문자열 컬럼만 따로 추출
test1 = test1.copy()

df_str = test1[['gender','car','reality','income_type','edu_type','family_type','house_type','occyp_type']]

for col in df_str:
    col = str(col)
    encoder = LabelEncoder()
    encoder.fit(test1[col])
    labels = encoder.transform(test1[col]) # 숫자 라벨 생성
    test1[col] = labels


In [117]:
test1

gender  car  reality  child_num  income_total  income_type  edu_type  \
index                                                                         
26457       1    1        0          0      112500.0            1         4   
26458       0    0        1          0      135000.0            2         1   
26459       0    0        1          0       69372.0            4         4   
26460       1    1        0          0      112500.0            0         4   
26461       0    1        1          0      225000.0            2         1   
...       ...  ...      ...        ...           ...          ...       ...   
36452       0    1        1          0      202500.0            4         2   
36453       1    1        1          0      202500.0            4         4   
36454       0    0        1          0      292500.0            4         4   
36455       0    1        0          0      180000.0            0         4   
36456       0    0        1          0      270000.0            4         1   

       family_type  house_type  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  \
index                                                                   
26457            0           1      -21990         365243           1   
26458            1           1      -18964          -8671           1   
26459            1           1      -15887           -217           1   
26460            1           1      -19270          -2531           1   
26461            1           1      -17822          -9385           1   
...            ...         ...         ...            ...         ...   
36452            1           1      -18593          -5434           1   
36453            0           1      -10886          -1315           1   
36454            1           1      -21016         -14018           1   
36455            1           1      -16541          -1085           1   
36456            1           1       -9154           -187           1   

       work_phone  phone  email  occyp_type  family_size  begin_month  
index                                                                  
26457           0      1      0          18          2.0        -60.0  
26458           0      1      0           3          2.0        -36.0  
26459           1      1      0           8          2.0        -40.0  
26460           1      0      0           4          2.0        -41.0  
26461           1      0      0          10          2.0         -8.0  
...           ...    ...    ...         ...          ...          ...  
36452           1      1      0           0          2.0        -19.0  
36453           1      0      0           8          2.0        -34.0  
36454           0      0      0          11          2.0        -55.0  
36455           0      1      0          18          2.0        -33.0  
36456           0      0      1           8          2.0        -11.0  

[10000 rows x 18 columns]

In [50]:
a = pd.DataFrame(model_final.predict_proba(test1))

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [47]:
sub = pd.read_csv('./creditcard/sample_submission.csv')

In [68]:
sub

index
0     26457
1     26458
2     26459
3     26460
4     26461
...     ...
9995  36452
9996  36453
9997  36454
9998  36455
9999  36456

[10000 rows x 1 columns]

In [59]:
sub = sub.drop(columns=['0','1','2'])

In [63]:
pd.concat([sub,a],axis=1).to_csv('result.csv',index=False)

In [64]:
model_final.score(test_X,test_y)

0.6921768707482994

In [84]:
model_RF.score(test_X,test_y)

0.7071050642479214

In [66]:
a = pd.DataFrame(model_final.predict_proba(test1))
pd.concat([sub,a],axis=1).to_csv('result.csv',index=False)

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [69]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
model_tree = DecisionTreeClassifier()

In [71]:
model_tree.fit(train_X,train_y)

DecisionTreeClassifier()

In [75]:
a= list(model_tree.feature_importances_)

In [76]:
b= list(df1.columns)

In [79]:
zip = list(zip(a,b))

In [81]:
zip = zip.sort()

In [82]:
zip

[(0.0, 'FLAG_MOBIL'),
 (0.009229933960730172, 'email'),
 (0.01160066485185337, 'edu_type'),
 (0.01255812103119503, 'gender'),
 (0.01270422493352157, 'child_num'),
 (0.012928326562922556, 'work_phone'),
 (0.014206064589816216, 'car'),
 (0.014838768648588107, 'phone'),
 (0.016628673895032486, 'house_type'),
 (0.018100151004348593, 'family_size'),
 (0.018937779552224657, 'income_type'),
 (0.02038277665802516, 'reality'),
 (0.026356848776486908, 'family_type'),
 (0.0551315314198547, 'occyp_type'),
 (0.0969135603990649, 'income_total'),
 (0.12179635348133529, 'DAYS_EMPLOYED'),
 (0.1765955822840267, 'DAYS_BIRTH'),
 (0.3610906379509735, 'begin_month')]

In [126]:
train_X = df1[['family_size','income_type','reality','family_type','income_total','DAYS_EMPLOYED','DAYS_BIRTH','begin_month']]
train_y = df1['credit']

In [127]:
test1 = test1[['family_size','income_type','reality','family_type','income_total','DAYS_EMPLOYED','DAYS_BIRTH','begin_month']]

In [128]:
train_X

family_size  income_type  reality  family_type  income_total  \
index                                                                 
0              2.0            0        0            1      202500.0   
1              3.0            0        1            0      247500.0   
2              2.0            4        1            1      450000.0   
3              2.0            0        1            1      202500.0   
4              2.0            2        1            1      157500.0   
...            ...          ...      ...          ...           ...   
26452          4.0            2        0            1      225000.0   
26453          2.0            4        1            2      180000.0   
26454          2.0            4        0            0      292500.0   
26455          1.0            4        1            3      171000.0   
26456          2.0            4        0            0       81000.0   

       DAYS_EMPLOYED  DAYS_BIRTH  begin_month  
index                                          
0              -4709      -13899         -6.0  
1              -1540      -11380         -5.0  
2              -4434      -19087        -22.0  
3              -2092      -15088        -37.0  
4              -2105      -15037        -26.0  
...              ...         ...          ...  
26452          -1984      -12079         -2.0  
26453          -2475      -15291        -47.0  
26454          -2015      -10082        -25.0  
26455           -107      -10145        -59.0  
26456          -1013      -19569         -9.0  

[26457 rows x 8 columns]

In [121]:
# 전체 데이터
#train_X,test_X,train_y,test_y = train_test_split(input_data,target,test_size = 0.2, stratify=target ,random_state=42 )

# 스케일링-------------------------------------------------------------------
from sklearn.preprocessing import StandardScaler
# 변형 객체 생성
std_scaler = StandardScaler()

# 훈련데이터의 모수 분포 저장
std_scaler.fit(train_X)

# 훈련 데이터 스케일링
train_X_scaled = std_scaler.transform(train_X)

# 테스트 데이터의 스케일링
test_X_scaled = std_scaler.transform(test_X)

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- car
- child_num
- edu_type
- email
- gender
- ...

  warnings.warn(message, FutureWarning)


ValueError: X has 17 features, but StandardScaler is expecting 9 features as input.

In [129]:
model_RF = RandomForestClassifier()
model_RF.fit(train_X,train_y)

RandomForestClassifier()

In [130]:
a = pd.DataFrame(model_RF.predict_proba(test1))
pd.concat([sub,a],axis=1).to_csv('result3.csv',index=False)